// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package company_mock

import (
	"context"

	"github.com/DanilaKorobkov/financial-analyst/internal/domain/aggregates/company"
	mock "github.com/stretchr/testify/mock"
)

// NewSecurityDescriptionSource creates a new instance of SecurityDescriptionSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecurityDescriptionSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecurityDescriptionSource {
	mock := &SecurityDescriptionSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SecurityDescriptionSource is an autogenerated mock type for the SecurityDescriptionSource type
type SecurityDescriptionSource struct {
	mock.Mock
}

type SecurityDescriptionSource_Expecter struct {
	mock *mock.Mock
}

func (_m *SecurityDescriptionSource) EXPECT() *SecurityDescriptionSource_Expecter {
	return &SecurityDescriptionSource_Expecter{mock: &_m.Mock}
}

// FindByTicker provides a mock function for the type SecurityDescriptionSource
func (_mock *SecurityDescriptionSource) FindByTicker(ctx context.Context, ticker string) (company.SecurityDescription, error) {
	ret := _mock.Called(ctx, ticker)

	if len(ret) == 0 {
		panic("no return value specified for FindByTicker")
	}

	var r0 company.SecurityDescription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (company.SecurityDescription, error)); ok {
		return returnFunc(ctx, ticker)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) company.SecurityDescription); ok {
		r0 = returnFunc(ctx, ticker)
	} else {
		r0 = ret.Get(0).(company.SecurityDescription)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ticker)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecurityDescriptionSource_FindByTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTicker'
type SecurityDescriptionSource_FindByTicker_Call struct {
	*mock.Call
}

// FindByTicker is a helper method to define mock.On call
//   - ctx context.Context
//   - ticker string
func (_e *SecurityDescriptionSource_Expecter) FindByTicker(ctx interface{}, ticker interface{}) *SecurityDescriptionSource_FindByTicker_Call {
	return &SecurityDescriptionSource_FindByTicker_Call{Call: _e.mock.On("FindByTicker", ctx, ticker)}
}

func (_c *SecurityDescriptionSource_FindByTicker_Call) Run(run func(ctx context.Context, ticker string)) *SecurityDescriptionSource_FindByTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SecurityDescriptionSource_FindByTicker_Call) Return(securityDescription company.SecurityDescription, err error) *SecurityDescriptionSource_FindByTicker_Call {
	_c.Call.Return(securityDescription, err)
	return _c
}

func (_c *SecurityDescriptionSource_FindByTicker_Call) RunAndReturn(run func(ctx context.Context, ticker string) (company.SecurityDescription, error)) *SecurityDescriptionSource_FindByTicker_Call {
	_c.Call.Return(run)
	return _c
}
