# mockery v3 — генератор mocks по Go-интерфейсам.
# Документация: https://vektra.github.io/mockery/latest/

all: true
recursive: true
formatter: goimports
template: testify
# yamllint disable-line rule:line-length
dir: mocks/{{ replaceAll "internal/" "internal_/" .InterfaceDirRelative }}
filename: "{{ .InterfaceName | snakecase }}.go"
pkgname: "{{ .SrcPackageName }}_mock"
structname: "{{ .InterfaceName }}"
packages:
  github.com/DanilaKorobkov/financial-analyst/internal: ~
