version: '3'

tasks:
  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  fmt:
    desc: Run golangci-lint with autofix (errors suppressed)
    cmds:
      - golangci-lint run --fix ./... || true
