// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package companycard_mock

import (
	"context"

	"github.com/DanilaKorobkov/financial-analyst/internal/domain/companycard"
	mock "github.com/stretchr/testify/mock"
)

// NewClassificationGateway creates a new instance of ClassificationGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClassificationGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClassificationGateway {
	mock := &ClassificationGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClassificationGateway is an autogenerated mock type for the ClassificationGateway type
type ClassificationGateway struct {
	mock.Mock
}

type ClassificationGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *ClassificationGateway) EXPECT() *ClassificationGateway_Expecter {
	return &ClassificationGateway_Expecter{mock: &_m.Mock}
}

// FindByTicker provides a mock function for the type ClassificationGateway
func (_mock *ClassificationGateway) FindByTicker(ctx context.Context, ticker string) (companycard.Classification, error) {
	ret := _mock.Called(ctx, ticker)

	if len(ret) == 0 {
		panic("no return value specified for FindByTicker")
	}

	var r0 companycard.Classification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (companycard.Classification, error)); ok {
		return returnFunc(ctx, ticker)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) companycard.Classification); ok {
		r0 = returnFunc(ctx, ticker)
	} else {
		r0 = ret.Get(0).(companycard.Classification)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ticker)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClassificationGateway_FindByTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTicker'
type ClassificationGateway_FindByTicker_Call struct {
	*mock.Call
}

// FindByTicker is a helper method to define mock.On call
//   - ctx context.Context
//   - ticker string
func (_e *ClassificationGateway_Expecter) FindByTicker(ctx interface{}, ticker interface{}) *ClassificationGateway_FindByTicker_Call {
	return &ClassificationGateway_FindByTicker_Call{Call: _e.mock.On("FindByTicker", ctx, ticker)}
}

func (_c *ClassificationGateway_FindByTicker_Call) Run(run func(ctx context.Context, ticker string)) *ClassificationGateway_FindByTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClassificationGateway_FindByTicker_Call) Return(classification companycard.Classification, err error) *ClassificationGateway_FindByTicker_Call {
	_c.Call.Return(classification, err)
	return _c
}

func (_c *ClassificationGateway_FindByTicker_Call) RunAndReturn(run func(ctx context.Context, ticker string) (companycard.Classification, error)) *ClassificationGateway_FindByTicker_Call {
	_c.Call.Return(run)
	return _c
}
