// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package companycard_mock

import (
	"context"

	"github.com/DanilaKorobkov/financial-analyst/internal/domain/companycard"
	mock "github.com/stretchr/testify/mock"
)

// NewIdentityGateway creates a new instance of IdentityGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentityGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentityGateway {
	mock := &IdentityGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IdentityGateway is an autogenerated mock type for the IdentityGateway type
type IdentityGateway struct {
	mock.Mock
}

type IdentityGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *IdentityGateway) EXPECT() *IdentityGateway_Expecter {
	return &IdentityGateway_Expecter{mock: &_m.Mock}
}

// FindByTicker provides a mock function for the type IdentityGateway
func (_mock *IdentityGateway) FindByTicker(ctx context.Context, ticker string) (companycard.Identity, error) {
	ret := _mock.Called(ctx, ticker)

	if len(ret) == 0 {
		panic("no return value specified for FindByTicker")
	}

	var r0 companycard.Identity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (companycard.Identity, error)); ok {
		return returnFunc(ctx, ticker)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) companycard.Identity); ok {
		r0 = returnFunc(ctx, ticker)
	} else {
		r0 = ret.Get(0).(companycard.Identity)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ticker)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IdentityGateway_FindByTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTicker'
type IdentityGateway_FindByTicker_Call struct {
	*mock.Call
}

// FindByTicker is a helper method to define mock.On call
//   - ctx context.Context
//   - ticker string
func (_e *IdentityGateway_Expecter) FindByTicker(ctx interface{}, ticker interface{}) *IdentityGateway_FindByTicker_Call {
	return &IdentityGateway_FindByTicker_Call{Call: _e.mock.On("FindByTicker", ctx, ticker)}
}

func (_c *IdentityGateway_FindByTicker_Call) Run(run func(ctx context.Context, ticker string)) *IdentityGateway_FindByTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IdentityGateway_FindByTicker_Call) Return(identity companycard.Identity, err error) *IdentityGateway_FindByTicker_Call {
	_c.Call.Return(identity, err)
	return _c
}

func (_c *IdentityGateway_FindByTicker_Call) RunAndReturn(run func(ctx context.Context, ticker string) (companycard.Identity, error)) *IdentityGateway_FindByTicker_Call {
	_c.Call.Return(run)
	return _c
}
