// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package companycard_mock

import (
	"context"

	"github.com/DanilaKorobkov/financial-analyst/internal/domain/companycard"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// FindByTicker provides a mock function for the type Repository
func (_mock *Repository) FindByTicker(ctx context.Context, exchange companycard.Exchange, ticker string) (companycard.Card, error) {
	ret := _mock.Called(ctx, exchange, ticker)

	if len(ret) == 0 {
		panic("no return value specified for FindByTicker")
	}

	var r0 companycard.Card
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, companycard.Exchange, string) (companycard.Card, error)); ok {
		return returnFunc(ctx, exchange, ticker)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, companycard.Exchange, string) companycard.Card); ok {
		r0 = returnFunc(ctx, exchange, ticker)
	} else {
		r0 = ret.Get(0).(companycard.Card)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, companycard.Exchange, string) error); ok {
		r1 = returnFunc(ctx, exchange, ticker)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_FindByTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTicker'
type Repository_FindByTicker_Call struct {
	*mock.Call
}

// FindByTicker is a helper method to define mock.On call
//   - ctx context.Context
//   - exchange companycard.Exchange
//   - ticker string
func (_e *Repository_Expecter) FindByTicker(ctx interface{}, exchange interface{}, ticker interface{}) *Repository_FindByTicker_Call {
	return &Repository_FindByTicker_Call{Call: _e.mock.On("FindByTicker", ctx, exchange, ticker)}
}

func (_c *Repository_FindByTicker_Call) Run(run func(ctx context.Context, exchange companycard.Exchange, ticker string)) *Repository_FindByTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 companycard.Exchange
		if args[1] != nil {
			arg1 = args[1].(companycard.Exchange)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_FindByTicker_Call) Return(card companycard.Card, err error) *Repository_FindByTicker_Call {
	_c.Call.Return(card, err)
	return _c
}

func (_c *Repository_FindByTicker_Call) RunAndReturn(run func(ctx context.Context, exchange companycard.Exchange, ticker string) (companycard.Card, error)) *Repository_FindByTicker_Call {
	_c.Call.Return(run)
	return _c
}
