// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package data_mock

import (
	"context"

	"github.com/DanilaKorobkov/financial-analyst/internal/domain/data"
	mock "github.com/stretchr/testify/mock"
)

// NewBundle creates a new instance of Bundle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBundle(t interface {
	mock.TestingT
	Cleanup(func())
}) *Bundle {
	mock := &Bundle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Bundle is an autogenerated mock type for the Bundle type
type Bundle struct {
	mock.Mock
}

type Bundle_Expecter struct {
	mock *mock.Mock
}

func (_m *Bundle) EXPECT() *Bundle_Expecter {
	return &Bundle_Expecter{mock: &_m.Mock}
}

// BundleID provides a mock function for the type Bundle
func (_mock *Bundle) BundleID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BundleID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Bundle_BundleID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BundleID'
type Bundle_BundleID_Call struct {
	*mock.Call
}

// BundleID is a helper method to define mock.On call
func (_e *Bundle_Expecter) BundleID() *Bundle_BundleID_Call {
	return &Bundle_BundleID_Call{Call: _e.mock.On("BundleID")}
}

func (_c *Bundle_BundleID_Call) Run(run func()) *Bundle_BundleID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Bundle_BundleID_Call) Return(s string) *Bundle_BundleID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Bundle_BundleID_Call) RunAndReturn(run func() string) *Bundle_BundleID_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function for the type Bundle
func (_mock *Bundle) Fetch(ctx context.Context, ticker string) (data.FieldValues, error) {
	ret := _mock.Called(ctx, ticker)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 data.FieldValues
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (data.FieldValues, error)); ok {
		return returnFunc(ctx, ticker)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) data.FieldValues); ok {
		r0 = returnFunc(ctx, ticker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(data.FieldValues)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ticker)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Bundle_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type Bundle_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - ticker string
func (_e *Bundle_Expecter) Fetch(ctx interface{}, ticker interface{}) *Bundle_Fetch_Call {
	return &Bundle_Fetch_Call{Call: _e.mock.On("Fetch", ctx, ticker)}
}

func (_c *Bundle_Fetch_Call) Run(run func(ctx context.Context, ticker string)) *Bundle_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Bundle_Fetch_Call) Return(fieldValues data.FieldValues, err error) *Bundle_Fetch_Call {
	_c.Call.Return(fieldValues, err)
	return _c
}

func (_c *Bundle_Fetch_Call) RunAndReturn(run func(ctx context.Context, ticker string) (data.FieldValues, error)) *Bundle_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// Fields provides a mock function for the type Bundle
func (_mock *Bundle) Fields() []data.FieldDescriptor {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Fields")
	}

	var r0 []data.FieldDescriptor
	if returnFunc, ok := ret.Get(0).(func() []data.FieldDescriptor); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]data.FieldDescriptor)
		}
	}
	return r0
}

// Bundle_Fields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fields'
type Bundle_Fields_Call struct {
	*mock.Call
}

// Fields is a helper method to define mock.On call
func (_e *Bundle_Expecter) Fields() *Bundle_Fields_Call {
	return &Bundle_Fields_Call{Call: _e.mock.On("Fields")}
}

func (_c *Bundle_Fields_Call) Run(run func()) *Bundle_Fields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Bundle_Fields_Call) Return(fieldDescriptors []data.FieldDescriptor) *Bundle_Fields_Call {
	_c.Call.Return(fieldDescriptors)
	return _c
}

func (_c *Bundle_Fields_Call) RunAndReturn(run func() []data.FieldDescriptor) *Bundle_Fields_Call {
	_c.Call.Return(run)
	return _c
}
