// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package data_mock

import (
	"github.com/DanilaKorobkov/financial-analyst/internal/domain/data"
	mock "github.com/stretchr/testify/mock"
)

// NewProvider creates a new instance of Provider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *Provider {
	mock := &Provider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

type Provider_Expecter struct {
	mock *mock.Mock
}

func (_m *Provider) EXPECT() *Provider_Expecter {
	return &Provider_Expecter{mock: &_m.Mock}
}

// Bundles provides a mock function for the type Provider
func (_mock *Provider) Bundles() []data.Bundle {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Bundles")
	}

	var r0 []data.Bundle
	if returnFunc, ok := ret.Get(0).(func() []data.Bundle); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]data.Bundle)
		}
	}
	return r0
}

// Provider_Bundles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bundles'
type Provider_Bundles_Call struct {
	*mock.Call
}

// Bundles is a helper method to define mock.On call
func (_e *Provider_Expecter) Bundles() *Provider_Bundles_Call {
	return &Provider_Bundles_Call{Call: _e.mock.On("Bundles")}
}

func (_c *Provider_Bundles_Call) Run(run func()) *Provider_Bundles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Provider_Bundles_Call) Return(bundles []data.Bundle) *Provider_Bundles_Call {
	_c.Call.Return(bundles)
	return _c
}

func (_c *Provider_Bundles_Call) RunAndReturn(run func() []data.Bundle) *Provider_Bundles_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type Provider
func (_mock *Provider) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Provider_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type Provider_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *Provider_Expecter) ID() *Provider_ID_Call {
	return &Provider_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *Provider_ID_Call) Run(run func()) *Provider_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Provider_ID_Call) Return(s string) *Provider_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Provider_ID_Call) RunAndReturn(run func() string) *Provider_ID_Call {
	_c.Call.Return(run)
	return _c
}
