// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package data_mock

import (
	"github.com/DanilaKorobkov/financial-analyst/internal/domain/data"
	mock "github.com/stretchr/testify/mock"
)

// NewRegistrar creates a new instance of Registrar. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistrar(t interface {
	mock.TestingT
	Cleanup(func())
}) *Registrar {
	mock := &Registrar{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Registrar is an autogenerated mock type for the Registrar type
type Registrar struct {
	mock.Mock
}

type Registrar_Expecter struct {
	mock *mock.Mock
}

func (_m *Registrar) EXPECT() *Registrar_Expecter {
	return &Registrar_Expecter{mock: &_m.Mock}
}

// Register provides a mock function for the type Registrar
func (_mock *Registrar) Register(bundle data.Bundle) error {
	ret := _mock.Called(bundle)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(data.Bundle) error); ok {
		r0 = returnFunc(bundle)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Registrar_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Registrar_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - bundle data.Bundle
func (_e *Registrar_Expecter) Register(bundle interface{}) *Registrar_Register_Call {
	return &Registrar_Register_Call{Call: _e.mock.On("Register", bundle)}
}

func (_c *Registrar_Register_Call) Run(run func(bundle data.Bundle)) *Registrar_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 data.Bundle
		if args[0] != nil {
			arg0 = args[0].(data.Bundle)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Registrar_Register_Call) Return(err error) *Registrar_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Registrar_Register_Call) RunAndReturn(run func(bundle data.Bundle) error) *Registrar_Register_Call {
	_c.Call.Return(run)
	return _c
}
