// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package company_mock

import (
	"context"

	"github.com/DanilaKorobkov/financial-analyst/internal/domain/aggregates/company"
	mock "github.com/stretchr/testify/mock"
)

// NewStockSource creates a new instance of StockSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStockSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *StockSource {
	mock := &StockSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StockSource is an autogenerated mock type for the StockSource type
type StockSource struct {
	mock.Mock
}

type StockSource_Expecter struct {
	mock *mock.Mock
}

func (_m *StockSource) EXPECT() *StockSource_Expecter {
	return &StockSource_Expecter{mock: &_m.Mock}
}

// FindByTicker provides a mock function for the type StockSource
func (_mock *StockSource) FindByTicker(ctx context.Context, ticker string, opts company.StockOptions) (company.Stock, error) {
	ret := _mock.Called(ctx, ticker, opts)

	if len(ret) == 0 {
		panic("no return value specified for FindByTicker")
	}

	var r0 company.Stock
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, company.StockOptions) (company.Stock, error)); ok {
		return returnFunc(ctx, ticker, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, company.StockOptions) company.Stock); ok {
		r0 = returnFunc(ctx, ticker, opts)
	} else {
		r0 = ret.Get(0).(company.Stock)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, company.StockOptions) error); ok {
		r1 = returnFunc(ctx, ticker, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StockSource_FindByTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTicker'
type StockSource_FindByTicker_Call struct {
	*mock.Call
}

// FindByTicker is a helper method to define mock.On call
//   - ctx context.Context
//   - ticker string
//   - opts company.StockOptions
func (_e *StockSource_Expecter) FindByTicker(ctx interface{}, ticker interface{}, opts interface{}) *StockSource_FindByTicker_Call {
	return &StockSource_FindByTicker_Call{Call: _e.mock.On("FindByTicker", ctx, ticker, opts)}
}

func (_c *StockSource_FindByTicker_Call) Run(run func(ctx context.Context, ticker string, opts company.StockOptions)) *StockSource_FindByTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 company.StockOptions
		if args[2] != nil {
			arg2 = args[2].(company.StockOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StockSource_FindByTicker_Call) Return(stock company.Stock, err error) *StockSource_FindByTicker_Call {
	_c.Call.Return(stock, err)
	return _c
}

func (_c *StockSource_FindByTicker_Call) RunAndReturn(run func(ctx context.Context, ticker string, opts company.StockOptions) (company.Stock, error)) *StockSource_FindByTicker_Call {
	_c.Call.Return(run)
	return _c
}
