// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package company_mock

import (
	"context"

	"github.com/DanilaKorobkov/financial-analyst/internal/domain/aggregates/company"
	mock "github.com/stretchr/testify/mock"
)

// NewStockSummarySource creates a new instance of StockSummarySource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStockSummarySource(t interface {
	mock.TestingT
	Cleanup(func())
}) *StockSummarySource {
	mock := &StockSummarySource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StockSummarySource is an autogenerated mock type for the StockSummarySource type
type StockSummarySource struct {
	mock.Mock
}

type StockSummarySource_Expecter struct {
	mock *mock.Mock
}

func (_m *StockSummarySource) EXPECT() *StockSummarySource_Expecter {
	return &StockSummarySource_Expecter{mock: &_m.Mock}
}

// FindByTicker provides a mock function for the type StockSummarySource
func (_mock *StockSummarySource) FindByTicker(ctx context.Context, ticker string) (company.StockSummary, error) {
	ret := _mock.Called(ctx, ticker)

	if len(ret) == 0 {
		panic("no return value specified for FindByTicker")
	}

	var r0 company.StockSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (company.StockSummary, error)); ok {
		return returnFunc(ctx, ticker)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) company.StockSummary); ok {
		r0 = returnFunc(ctx, ticker)
	} else {
		r0 = ret.Get(0).(company.StockSummary)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ticker)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StockSummarySource_FindByTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTicker'
type StockSummarySource_FindByTicker_Call struct {
	*mock.Call
}

// FindByTicker is a helper method to define mock.On call
//   - ctx context.Context
//   - ticker string
func (_e *StockSummarySource_Expecter) FindByTicker(ctx interface{}, ticker interface{}) *StockSummarySource_FindByTicker_Call {
	return &StockSummarySource_FindByTicker_Call{Call: _e.mock.On("FindByTicker", ctx, ticker)}
}

func (_c *StockSummarySource_FindByTicker_Call) Run(run func(ctx context.Context, ticker string)) *StockSummarySource_FindByTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StockSummarySource_FindByTicker_Call) Return(stockSummary company.StockSummary, err error) *StockSummarySource_FindByTicker_Call {
	_c.Call.Return(stockSummary, err)
	return _c
}

func (_c *StockSummarySource_FindByTicker_Call) RunAndReturn(run func(ctx context.Context, ticker string) (company.StockSummary, error)) *StockSummarySource_FindByTicker_Call {
	_c.Call.Return(run)
	return _c
}
