// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package company_mock

import (
	"context"

	"github.com/DanilaKorobkov/financial-analyst/internal/domain/aggregates/company"
	mock "github.com/stretchr/testify/mock"
)

// NewStockInfoSource creates a new instance of StockInfoSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStockInfoSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *StockInfoSource {
	mock := &StockInfoSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StockInfoSource is an autogenerated mock type for the StockInfoSource type
type StockInfoSource struct {
	mock.Mock
}

type StockInfoSource_Expecter struct {
	mock *mock.Mock
}

func (_m *StockInfoSource) EXPECT() *StockInfoSource_Expecter {
	return &StockInfoSource_Expecter{mock: &_m.Mock}
}

// FindByTicker provides a mock function for the type StockInfoSource
func (_mock *StockInfoSource) FindByTicker(ctx context.Context, ticker string) (company.StockInfo, error) {
	ret := _mock.Called(ctx, ticker)

	if len(ret) == 0 {
		panic("no return value specified for FindByTicker")
	}

	var r0 company.StockInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (company.StockInfo, error)); ok {
		return returnFunc(ctx, ticker)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) company.StockInfo); ok {
		r0 = returnFunc(ctx, ticker)
	} else {
		r0 = ret.Get(0).(company.StockInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ticker)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StockInfoSource_FindByTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTicker'
type StockInfoSource_FindByTicker_Call struct {
	*mock.Call
}

// FindByTicker is a helper method to define mock.On call
//   - ctx context.Context
//   - ticker string
func (_e *StockInfoSource_Expecter) FindByTicker(ctx interface{}, ticker interface{}) *StockInfoSource_FindByTicker_Call {
	return &StockInfoSource_FindByTicker_Call{Call: _e.mock.On("FindByTicker", ctx, ticker)}
}

func (_c *StockInfoSource_FindByTicker_Call) Run(run func(ctx context.Context, ticker string)) *StockInfoSource_FindByTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StockInfoSource_FindByTicker_Call) Return(stockInfo company.StockInfo, err error) *StockInfoSource_FindByTicker_Call {
	_c.Call.Return(stockInfo, err)
	return _c
}

func (_c *StockInfoSource_FindByTicker_Call) RunAndReturn(run func(ctx context.Context, ticker string) (company.StockInfo, error)) *StockInfoSource_FindByTicker_Call {
	_c.Call.Return(run)
	return _c
}
