// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package connect_mock

import (
	"github.com/DanilaKorobkov/financial-analyst/internal/domain/data"
	mock "github.com/stretchr/testify/mock"
)

// newFieldRegistry creates a new instance of fieldRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newFieldRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *fieldRegistry {
	mock := &fieldRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// fieldRegistry is an autogenerated mock type for the fieldRegistry type
type fieldRegistry struct {
	mock.Mock
}

type fieldRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *fieldRegistry) EXPECT() *fieldRegistry_Expecter {
	return &fieldRegistry_Expecter{mock: &_m.Mock}
}

// FieldByID provides a mock function for the type fieldRegistry
func (_mock *fieldRegistry) FieldByID(id data.Field) (data.FieldDescriptor, bool) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FieldByID")
	}

	var r0 data.FieldDescriptor
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(data.Field) (data.FieldDescriptor, bool)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(data.Field) data.FieldDescriptor); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(data.FieldDescriptor)
	}
	if returnFunc, ok := ret.Get(1).(func(data.Field) bool); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// fieldRegistry_FieldByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FieldByID'
type fieldRegistry_FieldByID_Call struct {
	*mock.Call
}

// FieldByID is a helper method to define mock.On call
//   - id data.Field
func (_e *fieldRegistry_Expecter) FieldByID(id interface{}) *fieldRegistry_FieldByID_Call {
	return &fieldRegistry_FieldByID_Call{Call: _e.mock.On("FieldByID", id)}
}

func (_c *fieldRegistry_FieldByID_Call) Run(run func(id data.Field)) *fieldRegistry_FieldByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 data.Field
		if args[0] != nil {
			arg0 = args[0].(data.Field)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *fieldRegistry_FieldByID_Call) Return(fieldDescriptor data.FieldDescriptor, b bool) *fieldRegistry_FieldByID_Call {
	_c.Call.Return(fieldDescriptor, b)
	return _c
}

func (_c *fieldRegistry_FieldByID_Call) RunAndReturn(run func(id data.Field) (data.FieldDescriptor, bool)) *fieldRegistry_FieldByID_Call {
	_c.Call.Return(run)
	return _c
}
