// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services_mock

import (
	"context"

	"github.com/DanilaKorobkov/financial-analyst/internal/domain/data"
	mock "github.com/stretchr/testify/mock"
)

// NewDataFetcher creates a new instance of DataFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataFetcher {
	mock := &DataFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DataFetcher is an autogenerated mock type for the DataFetcher type
type DataFetcher struct {
	mock.Mock
}

type DataFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *DataFetcher) EXPECT() *DataFetcher_Expecter {
	return &DataFetcher_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type DataFetcher
func (_mock *DataFetcher) Fetch(ctx context.Context, ticker string, fieldIDs []data.Field) (data.FieldValues, error) {
	ret := _mock.Called(ctx, ticker, fieldIDs)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 data.FieldValues
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []data.Field) (data.FieldValues, error)); ok {
		return returnFunc(ctx, ticker, fieldIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []data.Field) data.FieldValues); ok {
		r0 = returnFunc(ctx, ticker, fieldIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(data.FieldValues)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []data.Field) error); ok {
		r1 = returnFunc(ctx, ticker, fieldIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DataFetcher_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type DataFetcher_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - ticker string
//   - fieldIDs []data.Field
func (_e *DataFetcher_Expecter) Fetch(ctx interface{}, ticker interface{}, fieldIDs interface{}) *DataFetcher_Fetch_Call {
	return &DataFetcher_Fetch_Call{Call: _e.mock.On("Fetch", ctx, ticker, fieldIDs)}
}

func (_c *DataFetcher_Fetch_Call) Run(run func(ctx context.Context, ticker string, fieldIDs []data.Field)) *DataFetcher_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []data.Field
		if args[2] != nil {
			arg2 = args[2].([]data.Field)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DataFetcher_Fetch_Call) Return(fieldValues data.FieldValues, err error) *DataFetcher_Fetch_Call {
	_c.Call.Return(fieldValues, err)
	return _c
}

func (_c *DataFetcher_Fetch_Call) RunAndReturn(run func(ctx context.Context, ticker string, fieldIDs []data.Field) (data.FieldValues, error)) *DataFetcher_Fetch_Call {
	_c.Call.Return(run)
	return _c
}
