package structfielddocs_test

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"testing"

	"github.com/stretchr/testify/suite"
	"golang.org/x/tools/go/analysis"

	"github.com/DanilaKorobkov/financial-analyst/tools/structfielddocs"
)

type analyzerSuite struct{ suite.Suite }

func TestAnalyzerSuite(t *testing.T) {
	t.Parallel()
	suite.Run(t, new(analyzerSuite))
}

func (s *analyzerSuite) TestExportedFieldWithoutCommentIsReported() {
	got := s.run(`package p
type Company struct {
	Ticker string
}`)
	s.Equal([]string{
		"p.go:3:2: exported field Ticker of exported struct Company must have a doc comment",
	}, got)
}

func (s *analyzerSuite) TestExportedFieldWithDocCommentIsOK() {
	got := s.run(`package p
type Company struct {
	// Ticker — тикер.
	Ticker string
}`)
	s.Nil(got)
}

func (s *analyzerSuite) TestExportedFieldWithInlineCommentIsReported() {
	got := s.run(`package p
type Company struct {
	Ticker string // тикер бумаги
}`)
	s.Equal([]string{
		"p.go:3:2: exported field Ticker of exported struct Company must have a doc comment",
	}, got)
}

func (s *analyzerSuite) TestUnexportedFieldIsIgnored() {
	got := s.run(`package p
type Company struct {
	ticker string
}`)
	s.Nil(got)
}

func (s *analyzerSuite) TestUnexportedStructIsIgnored() {
	got := s.run(`package p
type internal struct {
	Field string
}`)
	s.Nil(got)
}

func (s *analyzerSuite) TestEmbeddedFieldIsIgnored() {
	got := s.run(`package p
type Base struct{}
type Wrapper struct {
	Base
}`)
	s.Nil(got)
}

func (s *analyzerSuite) TestAnonymousStructIsIgnored() {
	got := s.run(`package p
func f() any {
	return struct {
		Field string
	}{Field: "x"}
}`)
	s.Nil(got)
}

func (s *analyzerSuite) TestMultiNameFieldReportsEachExportedName() {
	got := s.run(`package p
type Company struct {
	Ticker, Name string
}`)
	s.ElementsMatch([]string{
		"p.go:3:2: exported field Ticker of exported struct Company must have a doc comment",
		"p.go:3:10: exported field Name of exported struct Company must have a doc comment",
	}, got)
}

func (s *analyzerSuite) TestMultiNameFieldWithDocCommentIsOK() {
	got := s.run(`package p
type Company struct {
	// Ticker, Name — тикер и имя.
	Ticker, Name string
}`)
	s.Nil(got)
}

func (s *analyzerSuite) TestMixedFieldsReportsOnlyMissing() {
	got := s.run(`package p
type Company struct {
	// Ticker — тикер.
	Ticker string
	Name string
	age int
}`)
	s.Equal([]string{
		"p.go:5:2: exported field Name of exported struct Company must have a doc comment",
	}, got)
}

func (s *analyzerSuite) TestGeneratedFileIsIgnored() {
	got := s.run(`// Code generated by something. DO NOT EDIT.

package p
type Company struct {
	Ticker string
}`)
	s.Nil(got)
}

func (s *analyzerSuite) TestStructInsideGroupDecl() {
	got := s.run(`package p
type (
	Foo struct {
		Bar string
	}
	Baz struct {
		// Qux — задокументировано.
		Qux string
	}
)`)
	s.Equal([]string{
		"p.go:4:3: exported field Bar of exported struct Foo must have a doc comment",
	}, got)
}

// helpers — ниже всех тестов

func (s *analyzerSuite) run(src string) []string {
	s.T().Helper()
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "p.go", src, parser.ParseComments)
	s.Require().NoError(err)

	var diags []string
	pass := &analysis.Pass{
		Analyzer: structfielddocs.Analyzer,
		Fset:     fset,
		Files:    []*ast.File{file},
		Report: func(d analysis.Diagnostic) {
			// В формате `file:line:col: message` — тот же вид, что
			// печатает singlechecker в реальном CLI, и тот же, что
			// ожидают IDE/grep-tools для перехода к месту репорта.
			pos := fset.Position(d.Pos)
			diags = append(diags, fmt.Sprintf("%s:%d:%d: %s", pos.Filename, pos.Line, pos.Column, d.Message))
		},
	}
	_, err = structfielddocs.Analyzer.Run(pass)
	s.Require().NoError(err)
	return diags
}
