// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package entities_mock

import (
	"context"

	"github.com/DanilaKorobkov/financial-analyst/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewCompanyMetricsRepository creates a new instance of CompanyMetricsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompanyMetricsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompanyMetricsRepository {
	mock := &CompanyMetricsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CompanyMetricsRepository is an autogenerated mock type for the CompanyMetricsRepository type
type CompanyMetricsRepository struct {
	mock.Mock
}

type CompanyMetricsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CompanyMetricsRepository) EXPECT() *CompanyMetricsRepository_Expecter {
	return &CompanyMetricsRepository_Expecter{mock: &_m.Mock}
}

// FindByTicker provides a mock function for the type CompanyMetricsRepository
func (_mock *CompanyMetricsRepository) FindByTicker(ctx context.Context, ticker string) (entities.CompanyMetrics, error) {
	ret := _mock.Called(ctx, ticker)

	if len(ret) == 0 {
		panic("no return value specified for FindByTicker")
	}

	var r0 entities.CompanyMetrics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.CompanyMetrics, error)); ok {
		return returnFunc(ctx, ticker)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.CompanyMetrics); ok {
		r0 = returnFunc(ctx, ticker)
	} else {
		r0 = ret.Get(0).(entities.CompanyMetrics)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ticker)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CompanyMetricsRepository_FindByTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTicker'
type CompanyMetricsRepository_FindByTicker_Call struct {
	*mock.Call
}

// FindByTicker is a helper method to define mock.On call
//   - ctx context.Context
//   - ticker string
func (_e *CompanyMetricsRepository_Expecter) FindByTicker(ctx interface{}, ticker interface{}) *CompanyMetricsRepository_FindByTicker_Call {
	return &CompanyMetricsRepository_FindByTicker_Call{Call: _e.mock.On("FindByTicker", ctx, ticker)}
}

func (_c *CompanyMetricsRepository_FindByTicker_Call) Run(run func(ctx context.Context, ticker string)) *CompanyMetricsRepository_FindByTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CompanyMetricsRepository_FindByTicker_Call) Return(companyMetrics entities.CompanyMetrics, err error) *CompanyMetricsRepository_FindByTicker_Call {
	_c.Call.Return(companyMetrics, err)
	return _c
}

func (_c *CompanyMetricsRepository_FindByTicker_Call) RunAndReturn(run func(ctx context.Context, ticker string) (entities.CompanyMetrics, error)) *CompanyMetricsRepository_FindByTicker_Call {
	_c.Call.Return(run)
	return _c
}
