// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package entities_mock

import (
	"context"

	"github.com/DanilaKorobkov/financial-analyst/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewCompanyRepository creates a new instance of CompanyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompanyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompanyRepository {
	mock := &CompanyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CompanyRepository is an autogenerated mock type for the CompanyRepository type
type CompanyRepository struct {
	mock.Mock
}

type CompanyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CompanyRepository) EXPECT() *CompanyRepository_Expecter {
	return &CompanyRepository_Expecter{mock: &_m.Mock}
}

// FindByTicker provides a mock function for the type CompanyRepository
func (_mock *CompanyRepository) FindByTicker(ctx context.Context, ticker string) (entities.Company, error) {
	ret := _mock.Called(ctx, ticker)

	if len(ret) == 0 {
		panic("no return value specified for FindByTicker")
	}

	var r0 entities.Company
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.Company, error)); ok {
		return returnFunc(ctx, ticker)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.Company); ok {
		r0 = returnFunc(ctx, ticker)
	} else {
		r0 = ret.Get(0).(entities.Company)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ticker)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CompanyRepository_FindByTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTicker'
type CompanyRepository_FindByTicker_Call struct {
	*mock.Call
}

// FindByTicker is a helper method to define mock.On call
//   - ctx context.Context
//   - ticker string
func (_e *CompanyRepository_Expecter) FindByTicker(ctx interface{}, ticker interface{}) *CompanyRepository_FindByTicker_Call {
	return &CompanyRepository_FindByTicker_Call{Call: _e.mock.On("FindByTicker", ctx, ticker)}
}

func (_c *CompanyRepository_FindByTicker_Call) Run(run func(ctx context.Context, ticker string)) *CompanyRepository_FindByTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CompanyRepository_FindByTicker_Call) Return(company entities.Company, err error) *CompanyRepository_FindByTicker_Call {
	_c.Call.Return(company, err)
	return _c
}

func (_c *CompanyRepository_FindByTicker_Call) RunAndReturn(run func(ctx context.Context, ticker string) (entities.Company, error)) *CompanyRepository_FindByTicker_Call {
	_c.Call.Return(run)
	return _c
}
